### PR TITLE
[minor] remove target files based on source events

### LINKED ISSUE #1: rn-link does not handle refactored file names well.
The way rn-link seemingly syncs changes between the code being linked and the source node_modules code breaks the metro bundler in cases where multiple files with similar paths exists. For example:

both `src/components/dropdown.js` and `src/components/dropdown/index.js` can be legally resolved by:
```js
import dropdown from './components/dropdown';
```

rn-link can trigger this if the linked code is refactored and files/paths are renamed differently than the code the lives in the node_modules of the source directory.

`projectA/node_modules/dropdown/dropdown.js`

`dropdown/src/dropdown/index.js`

running `rn-link ../dropdown` inside of `projectA` causes both file structures to exist in the `projectA/node_modules/dropdown` in this case.

### PR DESCRIPTION
**Pull request by Swaagie**
Fixed #1

### CODE REVIEW

**Comment by chrisajimenez** [comment]
Will this work even if the target file structure is different before `rn-link` is started?

Also: will the source `node_modules/module` continue to work once `rn-link` is terminated in this case?

**Comment by Swaagie** [comment]
1. Nope although I might argue that is out of scope. There might be some options to fix it. I'm assuming a clean `node_modules` installation before you start this the very first time. Additional changes after should be coming from the linked source. If you change files outside of the linked source (directly in target) then I'd say you are on your own. Open to suggestions on how to better handle this. 

2. Not sure I understand the question. Why wouldn't it? Assuming you made intentional changes to the source. Could you elaborate?

**Comment by chrisajimenez** [comment]
An example of what I meant:

1. `ProjectA/node_modules/fancy_button` links the `fancy_button` package.
2. The developer refactors the `fancy_button` package to have a` button/index.js` file instead of a `button.js`file.

Will terminating `rn-link` restore the old version of `fancy_button` in `ProjectA`? Or will a clean install be required? This might be out of scope for this PR, I was just wondering.

**Comment by Swaagie** [comment]
No terminating `rn-link` will not restore the old version. It based the change on the changed source, in your example `button/index.js`. A clean install would be required at all times even when working with regular symlinks. Not saying it is out of scope by definitions, but it would be doing a lot more than regular symlinks would as well.

Basically it would require `rn-link` to:
1. read the target in `node_modules` for any existing files
2. store them in memory
3. write the old files back on exit

Seeing lots of edge cases here and it might not even what consumers would always want.

Going to merge this as is to fix the removal from source at least :)

**Pull request merged**
